project:
  type: website
  output-dir: docs

website:
  title: "Piotr Stępień"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - edukacja.qmd
      - doswiadczenie.qmd

format:
  html:
    theme: 
      dark: solar
      light: minty
    css: styles.css
    toc: true
    page-layout: full


